---

mountrw:
    name: Remount rootfs read-write
    type: shell
    exec: "mount -o remount,rw /"

mountfstab:
    name: Mount devices from /etc/fstab
    type: shell
    exec: "mount -a"
    requires: mountrw
    provides: filesystem

hostname:
    name: Set hostname
    type: shell
    script: |
        if [ "$HOSTNAME" = "~auto" ]; then
            hostname `/bin/genhostname`
        else
            hostname $HOSTNAME
        fi
    env:
        HOSTNAME: ~auto
    requires: filesystem

udev:
    type: daemon
    exec: "/sbin/udevd --debug"
    requires: filesystem, hostname

cgroups:
    type: shell
    exec: "cgroupfs-mount"
    requires: mountrw

udevtrigger:
    name: Synthesizing the initial hotplug events
    type: shell
    exec: "udevadm trigger"
    requires: udev

udevsettle:
    name: Wait for devices to settle
    type: shell
    exec: "udevadm settle"
    requires: udevtrigger
    provides: devices

localstorage:
    type: shell
    exec: "/bin/preplocalstorage"
    requires: devices

network:
    type: shell
    script: |
        sleep $DELAY
        if [ "$METHOD" = "dhcp" ]; then
            /sbin/udhcpc -i $NETDEV -p /var/run/udhcpc.$NETDEV.pid
        elif [ "$METHOD" = "static" ]; then
            ip link set dev $NETDEV up
            ip addr add $ADDRESS/$PREFIX dev $NETDEV
            ip route add default via $ROUTER dev $NETDEV
            echo $ADDRESS > /tmp/ip
        fi
    restart_limit: 1
    env:
        NETDEV: eno1
        METHOD: dhcp
        ADDRESS: false
        PREFIX: false
        ROUTER: false
        DELAY: 0
    requires: devices

dockerd:
    type: daemon
    exec: "/usr/bin/dockerd"
    requires: cgroups, devices
    env:
        DOCKER_RAMDISK: true

tugger-service:
    type: daemon
    exec: "/usr/bin/tugger-service"
    requires: network
    env:
        TUGGER_API_KEY: changeme

networktime:
    type: daemon
    exec: "/usr/sbin/ntpd -dg"
    requires: network

tty2:
    type: daemon
    exec: "/sbin/getty 38400 tty2"
    restart_limit: -1
    requires: devices

chvt2:
    type: shell
    exec: chvt 2
    requires: tty2

tty3:
    type: daemon
    exec: "/sbin/getty 38400 tty3"
    restart_limit: -1
    requires: devices
