#!/bin/sh

# do some mounts early
mount -t devtmpfs none /dev
mkdir /dev/pts
mkdir /dev/shm
mount proc
mount -a

# set up loopback interface
ip link set dev lo up

# make sure we pass kargs to init
exec /usr/bin/init8js `cat /proc/cmdline`